server:
  port: 8082
spring:
  application:
    name: eureka-client-consumer
eureka:
  client:
    service-url:
      #eureka server地址
      defaultZone: http://localhost:8761/eureka/
  instance:
     # 自定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

